version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: foldex_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: foldex
    ports:
      - "5432:5432"
    volumes:
      - foldex_data:/var/lib/postgresql/data

volumes:
  foldex_data: # This ensures your data isn't deleted when the container stops