services:
  postgres:
    image: postgres:16-alpine
    container_name: foldex_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: foldex
    ports:
      - "5432:5432"
    volumes:
      - foldex_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: foldex_redis
    restart: always
    command: redis-server --maxmemory-policy noeviction --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - foldex_redis_data:/data

volumes:
  foldex_data:
  foldex_redis_data:
