/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNoteNoteIdRouteImport } from './routes/_app/note/$noteId'
import { Route as AppVideoVideoIdRouteImport } from './routes/_app/video/$videoId'

const SigninLazyRouteImport = createFileRoute('/signin')()
const AppChatIndexLazyRouteImport = createFileRoute('/_app/chat/')()
const AppChatChatIdLazyRouteImport = createFileRoute('/_app/chat/$chatId')()
const AppWatchIndexLazyRouteImport = createFileRoute('/_app/watch/')()
const AppWatchWatchIdLazyRouteImport = createFileRoute('/_app/watch/$watchId')()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexLazyRoute = AppChatIndexLazyRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/chat/index.lazy').then((d) => d.Route),
)
const AppChatChatIdLazyRoute = AppChatChatIdLazyRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/chat/$chatId.lazy').then((d) => d.Route),
)
const AppNoteNoteIdRoute = AppNoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoVideoIdRoute = AppVideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchIndexLazyRoute = AppWatchIndexLazyRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/watch/index.lazy').then((d) => d.Route),
)
const AppWatchWatchIdLazyRoute = AppWatchWatchIdLazyRouteImport.update({
  id: '/watch/$watchId',
  path: '/watch/$watchId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/watch/$watchId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/signin': typeof SigninLazyRoute
  '/note/$noteId': typeof AppNoteNoteIdRoute
  '/video/$videoId': typeof AppVideoVideoIdRoute
  '/chat/$chatId': typeof AppChatChatIdLazyRoute
  '/watch/$watchId': typeof AppWatchWatchIdLazyRoute
  '/chat/': typeof AppChatIndexLazyRoute
  '/watch/': typeof AppWatchIndexLazyRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninLazyRoute
  '/': typeof AppIndexRoute
  '/note/$noteId': typeof AppNoteNoteIdRoute
  '/video/$videoId': typeof AppVideoVideoIdRoute
  '/chat/$chatId': typeof AppChatChatIdLazyRoute
  '/watch/$watchId': typeof AppWatchWatchIdLazyRoute
  '/chat': typeof AppChatIndexLazyRoute
  '/watch': typeof AppWatchIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/note/$noteId': typeof AppNoteNoteIdRoute
  '/_app/video/$videoId': typeof AppVideoVideoIdRoute
  '/_app/chat/$chatId': typeof AppChatChatIdLazyRoute
  '/_app/watch/$watchId': typeof AppWatchWatchIdLazyRoute
  '/_app/chat/': typeof AppChatIndexLazyRoute
  '/_app/watch/': typeof AppWatchIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/note/$noteId'
    | '/video/$videoId'
    | '/chat/$chatId'
    | '/watch/$watchId'
    | '/chat/'
    | '/watch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/'
    | '/note/$noteId'
    | '/video/$videoId'
    | '/chat/$chatId'
    | '/watch/$watchId'
    | '/chat'
    | '/watch'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/'
    | '/_app/note/$noteId'
    | '/_app/video/$videoId'
    | '/_app/chat/$chatId'
    | '/_app/watch/$watchId'
    | '/_app/chat/'
    | '/_app/watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/note/$noteId': {
      id: '/_app/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof AppNoteNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video/$videoId': {
      id: '/_app/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof AppVideoVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watch/': {
      id: '/_app/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof AppWatchIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watch/$watchId': {
      id: '/_app/watch/$watchId'
      path: '/watch/$watchId'
      fullPath: '/watch/$watchId'
      preLoaderRoute: typeof AppWatchWatchIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppNoteNoteIdRoute: typeof AppNoteNoteIdRoute
  AppVideoVideoIdRoute: typeof AppVideoVideoIdRoute
  AppChatChatIdLazyRoute: typeof AppChatChatIdLazyRoute
  AppWatchWatchIdLazyRoute: typeof AppWatchWatchIdLazyRoute
  AppChatIndexLazyRoute: typeof AppChatIndexLazyRoute
  AppWatchIndexLazyRoute: typeof AppWatchIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppNoteNoteIdRoute: AppNoteNoteIdRoute,
  AppVideoVideoIdRoute: AppVideoVideoIdRoute,
  AppChatChatIdLazyRoute: AppChatChatIdLazyRoute,
  AppWatchWatchIdLazyRoute: AppWatchWatchIdLazyRoute,
  AppChatIndexLazyRoute: AppChatIndexLazyRoute,
  AppWatchIndexLazyRoute: AppWatchIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
